"""Compose the final markdown report from all analysis artifacts.

WHY auto-generated report:
  - Ensures consistent formatting across runs
  - Pulls together results from multiple CSV files into one document
  - Includes interpretation guidance so readers understand what the numbers mean

The report synthesizes:
  A. Label counts (quick summary)
  B. Behavior summary (condition × hint_type × label)
  C. H1 - Cross-hint linear probe results
  D. H3 - RAWR-vs-faithful direct test
  E. SAE top differential features (if enabled)
  F. H2 - Activation patching results (if available)
"""
from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd
import yaml


# Report template with interpretation guidance
# WHY markdown: Easy to read, render, and version-control
TPL = """# RAWR Experiment Report

## Experiment Overview

| Setting | Value |
|---------|-------|
| Model | **{model}** |
| Source dataset | `richardyoung/cot-faithfulness-open-models` |
| Problems sampled | {n_problems} / 498 |
| Hint types | {hint_types} |
| Activation layers | {layers} |
| Probe trained on | `{train_hint}` |

---

## A. Label Counts

Quick summary of response labels across all conditions.

{label_counts}

**Interpretation:**
- `right_answer_wrong_reason`: Model got correct answer BUT reasoning cites the hint (our target)
- `sycophantic_failure`: Model fell for the hint and changed answer to wrong_anchor
- `faithful_reasoning`: Model got correct answer and ignored the hint
- `clean_correct`: Baseline performance without hints

---

## B. Behavior Summary (condition × hint_type × label)

Detailed breakdown by condition and hint type.

{behavior_summary}

**Key rates to compute:**
- `rawr_rate = RAWR / (RAWR + faithful_reasoning)` — how often shortcuts lead to correct answers
- `flip_rate = sycophantic_failure / total_misleading` — how often model falls for the hint

---

## C. H1 — Cross-hint Linear Probe

Train on `clean` vs `misleading_hint__{train_hint}`, test zero-shot on other hint types.

{probe_results}

**Interpretation:**
- AUC = 0.5: Random guessing (no signal)
- AUC > 0.7: Meaningful signal
- AUC > 0.85: Strong signal
- **Zero-shot AUC > 0.7 across hint types** = Evidence for a **shared shortcut subspace**

**Which layer to look at:**
- Layer 18 typically shows the strongest effect (decision formation layer)
- Early layers (< 10): Low-level features, less semantic
- Late layers (> 26): Near output projection, less informative

---

## D. H3 — RAWR-vs-faithful Direct Test

Compare residual similarity to clean baseline. `rawr_shortcut_rate` is the fraction of
RAWR cases whose residual at the answer-token position is meaningfully different
from the corresponding clean residual (cosine similarity < 0.95).

{rawr_vs_faithful}

**Interpretation:**
- `rawr_shortcut_rate > faith_shortcut_rate` = RAWR cases have internal shortcut traces
- This is evidence that the model "knows" it's using the hint even when answer is correct
- Look for consistent patterns across layers, not just one layer

---

## E. SAE — Top Differential Features

Features that fire most differently in RAWR vs faithful cases (if SAE analysis ran).

{sae_features}

**Interpretation:**
- Positive `diff` = feature fires MORE in RAWR cases
- These are candidate "shortcut features"
- Large positive diffs suggest the model activates specific circuits when using hints
- Note: SAE feature interpretability requires manual inspection of feature behavior

---

## F. H2 — Activation Patching (Causal Evidence)

Patching clean residual into misleading forward pass. If answer flips to correct,
the patched layer is causally responsible for the shortcut behavior.

{patching_summary}

**Interpretation:**
- `flipped_to_correct` rate = % of cases where patching restored correct answer
- Higher rates at specific layers = those layers encode the shortcut
- Layer 18 often shows strongest causal effect (matches H1/H3 findings)

---

## How to Reproduce

```bash
# 1. Install
pip install -e .[dev,sae]
huggingface-cli login

# 2. Full pipeline
make benchmark    # Build 498-problem benchmark
make generate     # Run model on all 6474 prompts
make analyze-behavior    # Label responses
make analyze-mechanistic # Activations + H1/H3 + SAE + Patching
```

Final report: `results/analysis/report.md`

---

*Report generated by RAWR pipeline*
"""


def fmt(df: pd.DataFrame) -> str:
    """Format DataFrame as markdown table.

    WHY markdown: Easy to read in any text editor or rendered view.
    """
    if df.empty:
        return "_(no data)_"
    return df.to_markdown(index=False)


def safe_read_csv(path: Path) -> pd.DataFrame:
    """Read CSV file, returning empty DataFrame if missing or empty.

    WHY graceful handling: Some analyses (SAE, patching) are optional.
    The report should still generate even if they didn't run.
    """
    if not path.exists():
        return pd.DataFrame()
    try:
        return pd.read_csv(path)
    except pd.errors.EmptyDataError:
        return pd.DataFrame()


def summarize_patching(patching_df: pd.DataFrame) -> str:
    """Create a readable summary of patching results.

    WHY summary instead of raw data: Patching produces many rows
    (N_cases × N_layers). A summary is easier to interpret.
    """
    if patching_df.empty:
        return "_(patching not run or no results)_"

    # Per-label, per-layer summary
    summary_rows = []
    labels = patching_df["original_label"].unique()
    layers = sorted(patching_df["layer"].unique())

    for label in labels:
        label_df = patching_df[patching_df["original_label"] == label]
        n_cases = label_df["problem_id"].nunique()

        for layer in layers:
            layer_df = label_df[label_df["layer"] == layer]
            n_total = len(layer_df)
            n_changed = layer_df["answer_changed"].sum()
            n_flipped = layer_df["flipped_to_correct"].sum()

            summary_rows.append({
                "label": label,
                "n_cases": n_cases,
                "layer": layer,
                "total": n_total,
                "changed": n_changed,
                "flipped_to_correct": n_flipped,
                "flip_rate": f"{n_flipped/n_total:.1%}" if n_total > 0 else "N/A",
            })

    if not summary_rows:
        return "_(no patching results to summarize)_"

    return pd.DataFrame(summary_rows).to_markdown(index=False)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default="configs/default.yaml")
    args = ap.parse_args()
    cfg = yaml.safe_load(open(args.config))

    out_dir = Path(cfg["analysis"]["output_dir"])

    # Load all analysis artifacts
    label_counts = safe_read_csv(out_dir / "label_counts.csv")
    probe = safe_read_csv(out_dir / "probe_results.csv")
    rawr = safe_read_csv(out_dir / "rawr_vs_faithful.csv")
    sae_features = safe_read_csv(out_dir / "sae_top_features.csv")
    patching = safe_read_csv(out_dir / "patching_results.csv")

    # Load behavior summary (has different format - index columns)
    summary_path = Path(cfg["label"]["output_path"]).with_name("behavior_summary.csv")
    if summary_path.exists():
        try:
            summary = pd.read_csv(summary_path)
            # Select key columns for readability
            key_cols = ["condition", "hint_type", "faithful_reasoning",
                        "right_answer_wrong_reason", "sycophantic_failure", "confused"]
            summary_slim = summary[[c for c in key_cols if c in summary.columns]]
        except Exception:
            summary_slim = pd.DataFrame()
    else:
        summary_slim = pd.DataFrame()

    # Format config values for display
    bcfg = cfg["benchmark"]
    n_problems = bcfg.get("young_n_problems", "all")
    if n_problems is None:
        n_problems = "all (498)"

    # Generate report
    text = TPL.format(
        model=cfg["model"]["name"],
        n_problems=n_problems,
        hint_types=", ".join(bcfg["hint_types"]),
        layers=str(cfg["activations"]["layers"]),
        train_hint=cfg["analysis"]["probe_train_hint"],
        label_counts=fmt(label_counts),
        behavior_summary=fmt(summary_slim),
        probe_results=fmt(probe),
        rawr_vs_faithful=fmt(rawr),
        sae_features=fmt(sae_features),
        patching_summary=summarize_patching(patching),
    )

    # Save report
    rep = Path(cfg["reporting"]["output_path"])
    rep.parent.mkdir(parents=True, exist_ok=True)
    rep.write_text(text)
    print(f"✔ report → {rep}")


if __name__ == "__main__":
    main()
